# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc188c765eef2d047b1a1c8c8cdd7f0119711ebdd5dcdac43c2cd86adae14e02743df72cf5a719b40f95e7bf3b4a265eca3a02cba45a8fc4295c07df6326130d

test:
  secret_key_base: 79d30cacabdd6974356bc6c1cc1e3915e4aeec62e527842015bd1fa36476ffef2ea1ca82e02e344ed764c81bd10c22aa9a159cbe02986ea78e955e8ead9c244b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
